---
name: Build

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: build
    runs-on: [self-hosted, Linux]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6

      # The self-hosted runner already has Nix.
      - name: Build
        run: nix build .#default --print-build-logs
